### ISSUE TITLE
When tag list is empty then _buildField throws an unhandled exception

### ISSUE THREAD

**Issue by plumpNation** [Dn-a/flutter_tags#1]
To replicate, you should just be able to pass an empty List as `tags`.

```dart
      InputTags(
        tags: [],
        onDelete: () {},
        onInsert: () {}
      )
```

The error given is:

```
Unhandled exception:
Unsupported operation: Infinity or NaN toInt
#0      double.toInt (dart:core/runtime/libdouble.dart:178:36)
#1      double.ceil (dart:core/runtime/libdouble.dart:149:32)
#2      _InputTagsState.Eval (evaluate:source)
#3      _InputTagsState._buildField (package:flutter_tags/input_tags.dart:213:24)
```

You can also replicate by deleting all tags, which prints out this error.

```
flutter: Another exception was thrown: Unsupported operation: Infinity or NaN toInt
```

**Comment by Dn-a** [comment]
@plumpNation on the new version flutter tags: "^ 0.1.6" I solved the problem
