### ISSUE TITLE
Exception when using input decorator around InputTags

### ISSUE THREAD

**Issue by bzd2000** [Dn-a/flutter_tags#8]
In fact i would like to put an input decorator around the complete widget, so that i can draw a border around it and also toggle enable to make it read-only

```
 return Padding(
        padding: EdgeInsets.all(15.0),
        child: InputDecorator(
          decoration: InputDecoration(
            // icon: const Icon(Icons.color_lens),
            labelText: 'Duration',
            labelStyle: textStyle,
            enabled: true,
            border:
            OutlineInputBorder(borderRadius: BorderRadius.circular(5.0)),
          ),
          child: InputTags(
              tags: _tags,
              suggestionsList: _suggestionsList,
              onDelete: widget.onDelete,
              onInsert: widget.onInsert,
            ),
        ),
        );
```

But then i get this error
```
Initializing hot reload...
Syncing files to device Android SDK built for x86 64...
Reloaded 6 of 506 libraries in 3.025ms.
I/flutter (12150): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12150): The following assertion was thrown during performLayout():
I/flutter (12150): not implemented
I/flutter (12150): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 977 pos 12: 'false'
I/flutter (12150): 
I/flutter (12150): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12150): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12150): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12150):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12150): 
I/flutter (12150): When the exception was thrown, this was the stack:
I/flutter (12150): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart:977:12)
I/flutter (12150): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:98:20)
I/flutter (12150): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:98:20)
I/flutter (12150): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:98:20)
I/flutter (12150): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #18     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultComputeDistanceToHighestActualBaseline (package:flutter/src/rendering/box.dart:2229:32)
I/flutter (12150): #19     RenderStack.computeDistanceToActualBaseline (package:flutter/src/rendering/stack.dart:470:12)
I/flutter (12150): #20     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #21     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #22     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:98:20)
I/flutter (12150): #24     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #25     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #26     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #27     RenderShiftedBox.computeDistanceToActualBaseline (package:flutter/src/rendering/shifted_box.dart:56:22)
I/flutter (12150): #28     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #29     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #30     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #31     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultComputeDistanceToHighestActualBaseline (package:flutter/src/rendering/box.dart:2229:32)
I/flutter (12150): #32     RenderFlex.computeDistanceToActualBaseline (package:flutter/src/rendering/flex.dart:600:14)
I/flutter (12150): #33     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #34     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #35     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #36     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultComputeDistanceToFirstActualBaseline (package:flutter/src/rendering/box.dart:2211:35)
I/flutter (12150): #37     RenderFlex.computeDistanceToActualBaseline (package:flutter/src/rendering/flex.dart:601:12)
I/flutter (12150): #38     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #39     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #40     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:98:20)
I/flutter (12150): #42     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #43     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #44     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #45     RenderShiftedBox.computeDistanceToActualBaseline (package:flutter/src/rendering/shifted_box.dart:56:22)
I/flutter (12150): #46     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter (12150): #47     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (12150): #48     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter (12150): #49     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1655:27)
I/flutter (12150): #50     _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:820:35)
I/flutter (12150): #51     _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:858:18)
I/flutter (12150): #52     _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:987:44)
I/flutter (12150): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #54     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12150): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #60     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:410:13)
I/flutter (12150): #61     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
I/flutter (12150): #62     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
I/flutter (12150): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #64     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (12150): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #66     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (12150): #67     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (12150): #68     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (12150): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #86     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (12150): #87     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
I/flutter (12150): #88     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (12150): #89     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (12150): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #94     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (12150): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #98     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #100    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #102    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #104    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #108    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12150): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #110    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3030:14)
I/flutter (12150): #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (12150): #112    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (12150): #113    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter (12150): #114    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (12150): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter (12150): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (12150): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (12150): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (12150): #119    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (12150): #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (12150): #124    _invoke (dart:ui/hooks.dart:209:10)
I/flutter (12150): #125    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (12150): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (12150): 
I/flutter (12150): The following RenderObject was being processed when the exception was fired:
I/flutter (12150):   _RenderDecoration#ff88c relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12150):   creator: _Decorator ← InputDecorator ← Padding ← RecipeTags ← RepaintBoundary-[<2>] ←
I/flutter (12150):   IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ←
I/flutter (12150):   SliverList ← MediaQuery ← SliverPadding ← ⋯
I/flutter (12150):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (12150):   constraints: BoxConstraints(w=330.0, 0.0<=h<=Infinity)
I/flutter (12150):   size: MISSING
I/flutter (12150): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12150):   RenderPadding#59ba6 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (12150):     RenderDecoratedBox#aca5d relayoutBoundary=up8 NEEDS-PAINT
I/flutter (12150):       RenderFlex#cda2b relayoutBoundary=up9 NEEDS-PAINT
I/flutter (12150):         RenderFlex#c1ed4 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (12150):           RenderPadding#a7598 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (12150):   RenderTransform#1049b relayoutBoundary=up7 NEEDS-PAINT
I/flutter (12150):     RenderAnimatedOpacity#65b73 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (12150):       RenderParagraph#01a3d relayoutBoundary=up9 NEEDS-PAINT
I/flutter (12150):   RenderConstrainedBox#b10b2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12150):   RenderCustomPaint#4a64d NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12150): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#ff88c relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderPadding#a02eb relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d4e76 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#ff88c relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderPadding#a02eb relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d4e76 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#ff88c relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderPadding#a02eb relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d4e76 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/chatty  (12150): uid=10085(eu.delperdange.pmp_app) Thread-3 identical 2 lines
I/flutter (12150): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#ff88c relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderPadding#a02eb relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d4e76 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12150): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (12150): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was c
```

**Comment by bzd2000** [comment]
could be linked to this https://github.com/flutter/flutter/issues/24705

**Comment by Dn-a** [comment]
@bzd2000 new version 0.4.2.
check and leave feedback
